### ISSUE TITLE
fcrepo-api-x-registry fails to load if no configuration is provided

### ISSUE THREAD

**Issue by birkland** [fcrepo4-labs/fcrepo-api-x#119]
If no confugation `org.fcrepo.apix.registry.http.cfg` is provided to Karaf, the `fcrepo-api-x-registry` bundle will fail to load due to a NullPointerEception in blueprint. 

<pre>
2017-05-23 18:21:31,258 | ERROR | FelixStartLevel  | BlueprintContainerImpl           | 12 - org.apache.aries.blueprint.core - 1.6.2 | Unable to start blueprint container for bundle fcrepo-api-x-registry/0.3.0.SNAPSHOT
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to instantiate components
        at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:728)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:411)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:276)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:300)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:269)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:265)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:255)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)[21:org.apache.aries.util:1.1.1]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)[21:org.apache.aries.util:1.1.1]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)[21:org.apache.aries.util:1.1.1]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)[21:org.apache.aries.util:1.1.1]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)[21:org.apache.aries.util:1.1.1]
        at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1179)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.util.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:731)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:486)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4541)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2172)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)[org.apache.felix.framework-5.4.0.jar:]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
Caused by: java.lang.NullPointerException
        at org.apache.aries.blueprint.container.BeanRecipe.setProperties(BeanRecipe.java:910)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:844)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:811)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)[12:org.apache.aries.blueprint.core:1.6.2]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
        at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:255)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:186)[12:org.apache.aries.blueprint.core:1.6.2]
        at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:724)[12:org.apache.aries.blueprint.core:1.6.2]
</pre>

This is likely due to the following in blueprint:

    <bean id="configAdmin" factory-ref="conf" factory-method="getConfigAdmin" />
    <bean id="configuration" factory-ref="configAdmin" factory-method="getConfiguration">
        <argument value="org.fcrepo.apix.registry.http" />
    </bean>

A solution might be to edit the features file in order to provide a default `org.fcrepo.apix.registry.http.cfg` so that there is always a configurationAdmin available.

**Comment by ajs6f** [comment]
That would seem to work. In a much longer term sense, CDI-OSGi (and other systems) provide for optional OSGi config.

**Comment by whikloj** [comment]
I'm not sure if this is due to the Gradle build config, but for my Blueprint OSGI bundles I have a cfg in the `src/main/cfg` directory that seems to get deployed into the Karaf `/etc` automatically.

Alternatively, you could define default values in the the `property-placeholder` in case there is not a configuration file in place.
https://github.com/fcrepo4-labs/fcrepo-api-x/blob/master/fcrepo-api-x-registry/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L12-L18

**Comment by birkland** [comment]
@whikloj So it looks like a `<configfile>` directive can be added to karaf features, which causes it to deploy a config file.   The downiside is that  if that file is ever removed, BOOM.  So I ended up added a little helper programmatically which can deal with a null `ConfigurationAdmin`, or a null `Configuration`, or a null `Dictionary` of properties.  

It seems that there is no real elegant solution to getting the configuration properties using blueprint.  In declarative services, it's much more elegant:

    @Activate
    public void configure(Map<String, Object> properties) {
      ...
    }

**Comment by ajs6f** [comment]
Similarly in CDI-OSGi:
```
@OSGiComponent
public class MyComponent {
    public void updated(Dictionary config) {
    // eat optional config
    }
}
```
vs.
```
@OSGiComponent(requireConfiguration="PID.of.config")
public class MyComponent {
    public void updated(Dictionary config) {
    // eat required config
    }
}
```

Blueprint is starting to smell a bit musty.

**Comment by birkland** [comment]
Yeah, blueprint has ended up being a bit of a nightmare in practice.  It has been very costly in terms of debugging time and head scratching.

**Comment by ajs6f** [comment]
typesafety++

**Comment by birkland** [comment]
On that note, I've used [Declarative Services 1.3](http://njbartlett.name/2015/08/17/osgir6-declarative-services.html) before.  It's really neat, but also really unusual in how they use annotations for type-safe properties
