### ISSUE TITLE
Intermittent `java.lang.IllegalStateException: Connection pool shut down` when deploying features

### ISSUE THREAD

**Issue by dannylamb** [fcrepo4-labs/fcrepo-api-x#126]
From https://github.com/Islandora-CLAW/CLAW/issues/689

While testing the fixes required for a separate install issue, https://github.com/Islandora-CLAW/CLAW/issues/686, I ran into this every 10 or so times I set up Karaf with Api-X and Alpaca's custom http client.

```
2017-08-15 11:55:43,966 | INFO  | pool-52-thread-3 | InitMgr                          | 124 - fcrepo-api-x-jena - 0.3.0.SNAPSHOT | Caught exception while initializing.  Trying again in 1000 ms
java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)[54:org.apache.httpcomponents.httpcore:4.4.5]
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:185)[54:org.apache.httpcomponents.httpcore:4.4.5]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:257)[53:org.apache.httpcomponents.httpclient:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)[53:org.apache.httpcomponents.httpclient:4.5.3]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)[53:org.apache.httpcomponents.httpclient:4.5.3]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)[53:org.apache.httpcomponents.httpclient:4.5.3]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)[53:org.apache.httpcomponents.httpclient:4.5.3]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)[53:org.apache.httpcomponents.httpclient:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)[53:org.apache.httpcomponents.httpclient:4.5.3]
	at org.fcrepo.apix.registry.HttpClientFetcher$CloseableHttpClientProxy.doExecute(HttpClientFetcher.java:115)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)[53:org.apache.httpcomponents.httpclient:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)[53:org.apache.httpcomponents.httpclient:4.5.3]
	at org.fcrepo.apix.jena.impl.LdpContainerRegistry.exists(LdpContainerRegistry.java:280)
	at org.fcrepo.apix.jena.impl.LdpContainerRegistry.lambda$init$8(LdpContainerRegistry.java:131)
	at org.fcrepo.apix.jena.impl.InitMgr$1.lambda$$11(InitMgr.java:70)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
```

Are there any spots in Api-X where `ClosableResponse`s might not be getting closed properly?

**Comment by ajs6f** [comment]
I am currently checking the API-X code base to answer this question.

**Comment by birkland** [comment]
I'm giving it a glance too

**Comment by ajs6f** [comment]
@birkland , @dannylamb and I are in #islandora IRC if you need to grab us.

**Comment by ajs6f** [comment]
I think this might be weak config on [Islandora's injected client](https://github.com/Islandora-CLAW/Alpaca/blob/master/islandora-http-client/src/main/java/ca/islandora/alpaca/http/client/StaticTokenRequestInterceptor.java#L83).
